name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker buildx build --push --builder="multi-builder" --platform="linux/amd64" --tag="gegedesembri/telegram-bot-api:latest" --tag="gegedesembri/telegram-bot-api:0.3" .
